Culturale/culturale-server

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/cd.yml
.github/workflows/ci.yml

Set up the CI/CD flow for the applcation

Update CI/CD flow

---

Dockerfile
README.md
docker-compose.yml
package.json
src/infrastructure/api/user-routes.ts
src/server.ts
yarn.lock

The application was still not configured to use mongo and docker-compose wasn't connecting the app to it either.
Setup Mongo in the NodeJS app and update Docker to run it.

Setup MongoDB and Docker Compose to run the application

---

package.json
src/application/controllers/user-controller/user-controller.ts
src/application/use-cases/log-in/log-in.ts
src/domain/entities/user/__snapshots__/user.test.ts.snap
src/domain/entities/user/user.interface.ts
src/domain/entities/user/user.schema.ts
src/domain/entities/user/user.test.ts
src/domain/entities/user/user.ts
src/infrastructure/api/user-routes.ts
src/infrastructure/dtos/create-user.dto.ts
src/infrastructure/dtos/index.ts
src/infrastructure/dtos/login.dto.ts
src/infrastructure/index.ts
src/infrastructure/middlewares/auth/auth-middleware.ts
src/infrastructure/middlewares/auth/index.ts
src/infrastructure/middlewares/index.ts
yarn.lock

Until now users were not authenticated nor had a password to log in
- Add a password to user entity
- Encrypt password before storing it
- Add a middleware to pass to calls in order to authenticate through a token
- Add a login function to retrieve said token
1. Create a user with a password
2. Login with the created user
3. test the endpoint /test-user with authentication token putting the token from last call

Add user authentication

---

package.json
src/application/controllers/event-controller/event-controller.ts
src/domain/repositories/event-repository/event-repository.ts
src/infrastructure/api/event-router/event-router.test.ts
src/infrastructure/api/event-router/event-routes.ts
src/infrastructure/dtos/edit-event.dto.ts
src/infrastructure/dtos/index.ts
yarn.lock

**No pasa el test, pero no se hacerlo, se aceptan sugerencias :)** Todo lo demás hecho, tambien el merge con la última version de main para que no de problemas :p 
(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
Section dedicated to add any screenshots or other documents we find relevant …

22 modif evento

---

src/application/controllers/event-controller/event-controller.ts
src/application/use-cases/sign-up/sign-up.ts
src/infrastructure/api/event-router/event-router.test.ts

He añadido test new message
(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(Optional: List of dependencies or blockers that make this PR not yet ready to be merged with …

Test newMessage

---

src/application/controllers/event-controller/event-controller.test.ts
src/application/controllers/event-controller/event-controller.ts
src/application/use-cases/subscribe-event/subscribe.test.ts
src/application/use-cases/subscribe-event/subscribe.ts
src/domain/repositories/event-repository/event-repository.ts
src/infrastructure/api/event-router/event-router.test.ts
src/infrastructure/api/event-router/event-routes.ts

Añado test para el use case de subscribe usuario
(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(Optional: List of dependencies or blockers that make this PR not yet ready …

Chat tests

---

package.json
src/application/controllers/user-controller/user-controller.test.ts
src/application/controllers/user-controller/user-controller.ts
src/domain/repositories/user-repository/user-repository.ts
src/infrastructure/api/user-router/user-routes.test.ts
src/infrastructure/api/user-router/user-routes.ts
src/infrastructure/api/user-routes.ts
yarn.lock

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

funciona de manera local

---

src/application/use-cases/log-in/log-in.ts

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

Send info user login

---

src/application/controllers/event-controller/event-controller.test.ts
src/application/controllers/event-controller/event-controller.ts
src/application/controllers/user-controller/user-controller.ts
src/application/use-cases/makeEventReview/index.ts
src/application/use-cases/makeEventReview/makeReview.test.ts
src/application/use-cases/makeEventReview/makeReview.ts
src/domain/entities/event/__snapshots__/event.test.ts.snap
src/domain/entities/event/event.interface.ts
src/domain/entities/event/event.schema.ts
src/domain/entities/event/event.test.ts
src/domain/entities/event/event.ts
src/domain/entities/review/index.ts
src/domain/entities/review/review.interface.ts
src/domain/entities/review/review.schema.ts
src/domain/entities/review/review.ts
src/domain/repositories/event-repository/event-repository.ts
src/domain/repositories/review-repository/index.ts
src/domain/repositories/review-repository/review-repository.ts
src/domain/repositories/user-repository/user-repository.ts
src/infrastructure/api/event-router/event-routes.ts
src/infrastructure/dtos/create-event.dto.ts
src/infrastructure/dtos/make-review.dto.ts
test/setup-tests.ts
yarn.lock

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

Make Review with tests

---

src/application/controllers/user-controller/user-controller.test.ts
src/application/controllers/user-controller/user-controller.ts
src/application/use-cases/index.ts
src/application/use-cases/unfollow-user/index.ts
src/application/use-cases/unfollow-user/unfollow.ts
src/domain/entities/user/user.schema.ts
src/domain/entities/user/user.ts
src/domain/repositories/user-repository/user-repository.ts
src/infrastructure/api/user-router/user-routes.ts
src/infrastructure/dtos/follow.dto.ts
src/infrastructure/dtos/index.ts

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

delete followers y lista de usuarios unicos

---

src/application/controllers/event-controller/event-controller.test.ts
src/application/controllers/event-controller/event-controller.ts
src/domain/entities/event/event.ts
src/domain/entities/user/user.interface.ts
src/domain/repositories/user-repository/user-repository.ts
src/infrastructure/api/event-router/event-router.test.ts
src/infrastructure/api/event-router/event-routes.ts
src/infrastructure/api/user-router/user-routes.ts

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

Desapuntar evento user

---

src/application/controllers/event-controller/event-controller.test.ts
src/application/controllers/event-controller/event-controller.ts
src/application/controllers/user-controller/user-controller.test.ts
src/application/controllers/user-controller/user-controller.ts
src/application/use-cases/log-in/log-in.ts
src/application/use-cases/makeEventReview/makeReview.test.ts
src/application/use-cases/makeEventReview/makeReview.ts
src/domain/entities/review/review.interface.ts
src/domain/entities/review/review.schema.ts
src/domain/entities/review/review.ts
src/domain/entities/user/__snapshots__/user.test.ts.snap
src/domain/entities/user/user.interface.ts
src/domain/entities/user/user.schema.ts
src/domain/entities/user/user.ts
src/domain/repositories/review-repository/review-repository.ts
src/domain/repositories/user-repository/user-repository.ts
src/infrastructure/dtos/make-review.dto.ts

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

Add review to user

---

src/application/controllers/event-controller/event-controller.test.ts
src/application/controllers/event-controller/event-controller.ts
src/application/controllers/user-controller/user-controller.test.ts
src/application/controllers/user-controller/user-controller.ts
src/application/use-cases/log-in/log-in.ts
src/domain/entities/chat/__snapshots__/chat.test.ts.snap
src/domain/entities/chat/chat.interface.ts
src/domain/entities/chat/chat.ts
src/domain/entities/event/__snapshots__/event.test.ts.snap
src/domain/entities/event/event.interface.ts
src/domain/entities/event/event.ts
src/domain/entities/message/message.interface.ts
src/domain/entities/message/message.ts
src/domain/entities/review/review.interface.ts
src/domain/entities/review/review.ts
src/domain/entities/user/__snapshots__/user.test.ts.snap
src/domain/entities/user/user.interface.ts
src/domain/entities/user/user.ts
src/infrastructure/api/user-router/user-routes.test.ts

Domain entities had the property of id, but mongo stored it as "_id".
Update domain entities to have the _id property as mongo and add a get method to return id as string

Change id properties of domain entitites

---

src/application/controllers/event-controller/event-controller.test.ts
src/application/controllers/event-controller/event-controller.ts
src/application/use-cases/makeEventReview/makeReview.test.ts
src/domain/entities/event/__snapshots__/event.test.ts.snap
src/domain/entities/event/event.interface.ts
src/domain/entities/event/event.schema.ts
src/domain/entities/event/event.test.ts
src/domain/entities/event/event.ts
src/infrastructure/api/event-router/event-router.test.ts
src/infrastructure/dtos/create-event.dto.ts
src/infrastructure/dtos/edit-event.dto.ts

valores que actualmente puede tener caregoria: 
| 'agenda:categories/activitats-virtuals'
| 'agenda:categories/exposicions'
| 'agenda:categories/concerts'
| 'agenda:categories/teatre'
| 'agenda:categories/festivals-i-mostres'
| 'agenda:categories/rutes-i-visites'
| 'agenda:categories/infantil'
| 'agenda:categories/festes'
| 'agenda:categories/conferencies'
| 'agenda:categories/fires-i-mercats'
| 'agenda:categories/dansa'
| 'agenda:categories/cicles';
ASI ES EL VALOR QUE LEE DE LA BDD

Caregories

---

src/application/controllers/event-controller/event-controller.ts
src/domain/repositories/event-repository/event-repository.ts
src/infrastructure/api/event-router/event-routes.ts
src/infrastructure/api/event-routes.ts
src/infrastructure/api/user-routes.ts

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

#be filtratge events

---

.github/workflows/cd.yml
.github/workflows/k8s-cd.yml
k8s/culturale-ingress.yml
k8s/culturale-server.yml
k8s/mongodb-config.yml
k8s/mongodb-deployment.yml
k8s/mongodb-pvc.yml
k8s/mongodb-secret.yml
k8s/server-config.yml
k8s/server-secret.yml
k8s/storage-class.yml

The Kubernetes deployment files were not on the server repo.
Add the K8s deployment files to the repository as the first step for the deployment.

Set up K8s deployment files

---

src/application/controllers/user-controller/user-controller.test.ts
src/application/controllers/user-controller/user-controller.ts

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

añadido cambio follow uc

---

src/application/controllers/user-controller/user-controller.ts
src/application/use-cases/like-event/like.ts
src/domain/entities/user/__snapshots__/user.test.ts.snap
src/domain/entities/user/user.interface.ts
src/domain/entities/user/user.schema.ts
src/domain/entities/user/user.ts
src/domain/repositories/user-repository/user-repository.ts
src/infrastructure/api/user-router/user-routes.ts
src/infrastructure/dtos/addFavourite.dto.ts
src/infrastructure/dtos/index.ts

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

cas d'us implementat

---

src/application/controllers/user-controller/user-controller.ts
src/infrastructure/api/user-router/user-routes.ts

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

user by id

---

package-lock.json
package.json
src/domain/repositories/event-repository/event-repository.ts
yarn.lock

(Optional)
(Optional)
(Optional)
(Optional)
(Optional)
</details>
(List of …

quitar html
